[package]
name = "axum-es"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.40.0", features = ["full"] }
tower = "0.5.1"
dotenv = "0.15.0"
elasticsearch  = "8.5.0-alpha.1"
serde = "1.0.209"
serde_json = "1.0.127"